AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-reaction-rl
  
  Sample SAM Template for slack-reaction-rl

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  ReactedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: reacted/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          NOTION_API_KEY_PATH: "/rl/NOTION_API_KEY"
          NOTION_DATABASE_ID_PATH: "/rl/NOTION_DATABASE_ID"
          SLACK_BOT_TOKEN_PATH: "/rl/SLACK_BOT_TOKEN"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: rl/*
      FunctionUrlConfig:
        AuthType: NONE
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ReactedFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt ReactedFunction.Arn
  ReactedFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ReactedFunctionRole.Arn
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt ReactedFunctionUrl.FunctionUrl
